"""nyrahost.tools.doc_from_code — Phase 14-G whole-project doc agent.

Reads UCLASS / USTRUCT / UFUNCTION headers and renders one Markdown
file per module under ``Docs/<Module>.md``. Tier 2 moat — Aura
doesn't ship this; the per-event SaaS cost on a 2K-class project
would dwarf any reasonable doc budget.

v0 extracts:
  * UCLASS / USTRUCT name + base class
  * UPROPERTY / UFUNCTION declarations (top-level, no inline impls)
  * Doxygen-style /** ... */ doc comments immediately above each
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final, Optional

import structlog

log = structlog.get_logger("nyrahost.tools.doc_from_code")

ERR_BAD_INPUT: Final[int] = -32602
ERR_DOCGEN_FAILED: Final[int] = -32061

DOC_BLOCK_RE: Final[re.Pattern[str]] = re.compile(
    r"/\*\*\s*(?P<doc>(?:[^*]|\*(?!/))*)\*/\s*",
    re.DOTALL,
)
UCLASS_DECL_RE: Final[re.Pattern[str]] = re.compile(
    r"(?P<doc>/\*\*[\s\S]*?\*/\s*)?"
    r"UCLASS\([^)]*\)\s*"
    r"class\s+\w+_API\s+(?P<class_name>\w+)\s*:?\s*[^{]*",
    re.MULTILINE,
)
USTRUCT_DECL_RE: Final[re.Pattern[str]] = re.compile(
    r"(?P<doc>/\*\*[\s\S]*?\*/\s*)?"
    r"USTRUCT\([^)]*\)\s*"
    r"struct\s+\w+_API\s+(?P<struct_name>\w+)",
    re.MULTILINE,
)
UPROP_RE: Final[re.Pattern[str]] = re.compile(
    r"(?P<doc>/\*\*[\s\S]*?\*/\s*)?"
    r"UPROPERTY\([^)]*\)\s*"
    r"(?P<decl>[^;]+);",
    re.MULTILINE,
)
UFUNC_RE: Final[re.Pattern[str]] = re.compile(
    r"(?P<doc>/\*\*[\s\S]*?\*/\s*)?"
    r"UFUNCTION\([^)]*\)\s*"
    r"(?P<sig>[^;{]+)[;{]",
    re.MULTILINE,
)


@dataclass
class CodeMember:
    kind: str        # "uclass" | "ustruct" | "uproperty" | "ufunction"
    name: str
    decl: str
    doc: str = ""    # raw Doxygen body, stripped of leading * tokens


def _clean_doc(raw: str | None) -> str:
    if not raw:
        return ""
    # Strip /** and */; flatten leading * on each line.
    body = raw.strip()
    body = body.lstrip("/*").rstrip("*/").strip()
    out_lines = []
    for line in body.splitlines():
        s = line.strip()
        if s.startswith("*"):
            s = s[1:].strip()
        out_lines.append(s)
    return "\n".join(out_lines).strip()


def parse_header(text: str) -> list[CodeMember]:
    """Return UCLASS / USTRUCT / UPROPERTY / UFUNCTION members in order."""
    out: list[CodeMember] = []
    for m in UCLASS_DECL_RE.finditer(text):
        out.append(CodeMember(
            kind="uclass",
            name=m.group("class_name"),
            decl=m.group(0).strip(),
            doc=_clean_doc(m.group("doc")),
        ))
    for m in USTRUCT_DECL_RE.finditer(text):
        out.append(CodeMember(
            kind="ustruct",
            name=m.group("struct_name"),
            decl=m.group(0).strip(),
            doc=_clean_doc(m.group("doc")),
        ))
    for m in UPROP_RE.finditer(text):
        decl = m.group("decl").strip()
        # Pull last word as the prop name (handles `int32 Foo`, `TArray<X> Bar`).
        name = decl.split()[-1].rstrip(";")
        out.append(CodeMember(
            kind="uproperty",
            name=name,
            decl=decl,
            doc=_clean_doc(m.group("doc")),
        ))
    for m in UFUNC_RE.finditer(text):
        sig = m.group("sig").strip()
        # Function name: token before the first '('.
        if "(" in sig:
            head = sig.split("(", 1)[0]
            name = head.split()[-1]
        else:
            name = sig.split()[-1]
        out.append(CodeMember(
            kind="ufunction",
            name=name,
            decl=sig,
            doc=_clean_doc(m.group("doc")),
        ))
    return out


def render_module_md(module: str, members_by_file: dict[Path, list[CodeMember]]) -> str:
    """Render a Markdown doc for one UE module."""
    out: list[str] = [f"# `{module}` — auto-generated reference\n"]
    out.append(
        "> Generated by NYRA Phase 14-G doc-from-code agent. "
        "Each section comes from a Doxygen-style `/** ... */` "
        "block above the relevant declaration.\n"
    )
    for header_path, members in sorted(members_by_file.items()):
        out.append(f"\n## `{header_path.name}`\n")
        for m in members:
            doc = m.doc or "_(no docstring)_"
            out.append(f"\n### `{m.kind}` `{m.name}`\n")
            out.append(f"```cpp\n{m.decl}\n```\n")
            out.append(f"\n{doc}\n")
    return "".join(out)


def _err(code: int, message: str, detail: str = "", remediation: Optional[str] = None) -> dict:
    data: dict = {}
    if detail:
        data["detail"] = detail
    if remediation:
        data["remediation"] = remediation
    out: dict = {"error": {"code": code, "message": message}}
    if data:
        out["error"]["data"] = data
    return out


class DocFromCodeHandlers:
    def __init__(self, *, plugin_source_dir: Path) -> None:
        self._src = Path(plugin_source_dir)

    async def on_scan_module(self, params: dict, session=None, ws=None) -> dict:
        module = params.get("module")
        if not isinstance(module, str) or not module:
            return _err(ERR_BAD_INPUT, "missing_field", "module")
        root = self._src / module / "Public"
        if not root.exists():
            return _err(ERR_BAD_INPUT, "module_not_found", str(root))
        members_by_file: dict[Path, list[CodeMember]] = {}
        for h in sorted(root.rglob("*.h")):
            try:
                text = h.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            members = parse_header(text)
            if members:
                members_by_file[h] = members
        md = render_module_md(module, members_by_file)
        return {
            "module": module,
            "files_scanned": sum(1 for _ in root.rglob("*.h")),
            "files_with_decls": len(members_by_file),
            "markdown": md,
        }


__all__ = [
    "DocFromCodeHandlers",
    "CodeMember",
    "parse_header",
    "render_module_md",
    "ERR_BAD_INPUT",
    "ERR_DOCGEN_FAILED",
]
