// =============================================================================
// SNyraMessageList.h  (Phase 1 Plan 12 -- chat panel streaming integration)
// =============================================================================
//
// Virtualized list of chat message rows, backed by SListView<TSharedPtr<FNyraMessage>>.
// Rows are generated by GenerateRow which applies the RESEARCH Sec 3.1
// streaming strategy:
//   - Status == Done      -> SRichTextBlock + FNyraMarkdownParser output
//                             + FNyraCodeBlockDecoratorImpl decorator
//   - Status == Failed    -> red-tinted STextBlock rendering ErrorRemediation
//   - otherwise           -> plain STextBlock rendering StreamingBuffer
//
// Public ops:
//   - AppendMessage          -> adds a row + scrolls to bottom
//   - UpdateMessageStreaming -> appends delta to matching ReqId row + refreshes
//   - FinalizeMessage        -> transitions Streaming->Done/Cancelled/Failed
//   - FindByReqId            -> linear search for the row matching a ReqId
//   - ClearMessages          -> empties the list (used by Plan 12b's
//                                OpenConversation rebuild path)
//
// Extension points for Plan 12b (history-drawer):
//   - GenerateRow is protected + virtual so Plan 12b can override row
//     styling if it wants conversation-title headers between boundary rows.
//   - MakeBodyWidget is protected + virtual so Plan 12b can inject a
//     different decorator list (e.g. adding a heading decorator) without
//     touching Plan 12's GenerateRow body.
//   - ClearMessages is provided up-front so Plan 12b's SNyraChatPanel
//     OpenConversation can repopulate from a sessions/load snapshot.
//
// Thread safety: SNyraMessageList is GameThread-only. Callers that receive
// chat/stream notifications off-thread must marshal back via
// AsyncTask(ENamedThreads::GameThread, ...) -- Plan 10's FNyraSupervisor
// OnNotification delegate fires on the WS thread.
// =============================================================================

#pragma once

#include "CoreMinimal.h"
#include "Widgets/SCompoundWidget.h"
#include "Widgets/Views/SListView.h"
#include "Panel/NyraMessageModel.h"

/** Fired when the user clicks an individual message's per-row Cancel button
 *  during streaming. Passed back to SNyraChatPanel to emit chat/cancel. */
DECLARE_DELEGATE_OneParam(FOnMessageCancel, const TSharedPtr<FNyraMessage>& /*Msg*/);

class NYRAEDITOR_API SNyraMessageList : public SCompoundWidget
{
public:
    SLATE_BEGIN_ARGS(SNyraMessageList) {}
        SLATE_EVENT(FOnMessageCancel, OnCancel)
    SLATE_END_ARGS()

    void Construct(const FArguments& InArgs);

    /** Append a new message row and scroll the list to the bottom. */
    void AppendMessage(const TSharedPtr<FNyraMessage>& Msg);

    /** Append a chat/stream delta to the row matching the ReqId. */
    void UpdateMessageStreaming(const FGuid& ReqId, const FString& Delta);

    /** Finalize the row matching the ReqId. Pass bCancelled=true for
     *  chat/cancel, or Remediation non-empty for an error frame; otherwise
     *  the row transitions to Done and renders via SRichTextBlock. */
    void FinalizeMessage(const FGuid& ReqId, const FString& FinalContent, bool bCancelled, const FString& Remediation);

    /** Linear search for a row with a matching ReqId. */
    TSharedPtr<FNyraMessage> FindByReqId(const FGuid& ReqId) const;

    /** Clear all rows. Used by SNyraChatPanel::OpenConversation (Plan 12b). */
    void ClearMessages();

    /** Test hook: direct access to the backing array count + last entry. */
    int32 NumMessages() const { return Messages.Num(); }
    TSharedPtr<FNyraMessage> LastMessage() const { return Messages.IsValidIndex(Messages.Num()-1) ? Messages.Last() : nullptr; }

protected:
    /** Row factory -- virtual so Plan 12b can inject conversation separator rows. */
    virtual TSharedRef<ITableRow> GenerateRow(TSharedPtr<FNyraMessage> InItem, const TSharedRef<STableViewBase>& OwnerTable);

    /** Body widget builder -- virtual so Plan 12b can inject additional
     *  decorators (heading / link / inline-code) without overriding the
     *  entire row layout. */
    virtual TSharedRef<SWidget> MakeBodyWidget(const TSharedPtr<FNyraMessage>& InItem) const;

    TArray<TSharedPtr<FNyraMessage>> Messages;
    TSharedPtr<SListView<TSharedPtr<FNyraMessage>>> ListView;
    FOnMessageCancel OnCancelDelegate;
};
